In [1]:
import os
import errno
import glob
import shutil
import scipy.io as io
import cv2
import numpy as np
import matplotlib.pyplot as plt
import sys
import re

# import location for specific functions
path_to_face_front_utilyties = '/home/gonzalo/M9/Methods/face-frontalization'
sys.path.append(path_to_face_front_utilyties)
import check_resources as check
import frontalize
import facial_feature_detector as feature_detection
import camera_calibration as calib

#Identify OS platform 
#print os.name
import platform
working_platform = platform.system()
working_release = platform.release()
print working_platform




Linux


In [2]:
##################################################################
# Subssidiary functions #
##################################################################

def make_sure_path_exists(directory):
    if not os.path.exists(directory):
        try:
            os.makedirs(directory)
        except OSError as error:
            if error.errno != errno.EEXIST:
                raise
                
def make_sure_file_exists(infile):
    if not os.path.isfile(infile):
        try:
            with open(infile, 'w') as f:
                print 'file found...'
        except OSError as error:
            if error.errno != errno.EEXIST:
                raise

def seek_or_write(infile, searched_path, personID):
    with open(infile, "r+") as f:
        line_found = any(searched_path in line for line in f)
        if not line_found:
            f.seek(0, os.SEEK_END)
            f.write('%s %s\n' % (searched_path, personID))
        else:
            print 'file already listed'

In [3]:
# This function implements Haar face cascade method for face detection as in:
# https://www.superdatascience.com/opencv-face-detection/
# With modifications to only output the biggest bounding box as the face detection 
# (works on this particular case due to the nature of the dataset used as there is only one face per image)
def detect_face(gray_img, haar_face_cascade):
    roi_size_old = 0
    list_counter = 0
    biggest_val_index = 0
    face_area = ()
    faces = haar_face_cascade.detectMultiScale(gray_img, scaleFactor=1.1, minNeighbors=5);
    #print the number of faces found 
    print 'Faces found: ', len(faces)
    print faces
    if len(faces)==0:
        print 'none faces found'
    elif len(faces)==1:
        face_area = faces[list_counter]
        img_w_face = gray_img[face_area[0]:face_area[0]+face_area[2], face_area[1]:face_area[1]+face_area[3]]
        return img_w_face
    else:
        for (x, y, w, h) in faces:
            #print (x, y, w, h)
            roi_size = int(w) * int(h)
            #print 'current roi',roi_size, ' and old roi =', roi_size_old
            if roi_size < roi_size_old:
                roi_size = roi_size_old
            #    print 'new roi_size_old = ', roi_size_old
                biggest_val_index = biggest_val_index
            #    print list_counter
            else:
                roi_size_old = roi_size
            #    print 'new roi_size_old = ', roi_size_old
                biggest_val_index += list_counter
            #    print list_counter
            list_counter += 1
            face_area = faces[biggest_val_index]          
            img_w_face = gray_img[face_area[0]:face_area[0]+face_area[2], face_area[1]:face_area[1]+face_area[3]]
        return img_w_face

In [18]:
def front_database_build(name, data_path, work_path, mode, eyemask, filelist):
    ''' 
    Given the name of the subject in the variable -name-, the path from where to obtain the images, 
    the path to the destiny folder in which to save the database and the eyemask parameter used for
    frontalization of the faces, this routine takes the images from data_path and saves the 
    frontalized face obtained in the work_path separating pictures in folders for each individual. 
    '''
    for x in name[:]:
        pathdir = os.path.join(work_path, mode, x)
    
        print pathdir #for debug purposes
        make_sure_path_exists(pathdir)
        search_filename = x +  "*.pgm" # "*.jpg" #
        search_location = os.path.join(data_path,search_filename)
        print search_location #for debug purposes
    
        for filepath in glob.glob(search_location):
            
            # Extract filename from the filepath found at search location
            tail = re.split(r"[.]", os.path.basename(filepath))
            tail = str(tail[0])
            print tail #for debug purposes
            out_name = tail + 'fr.jpg'
            
            # For MIT-CBCL dataset file naming, break name into the image data provided in filename
            # 'subject' - 'face rotation' - etc
            file_data = re.split(r"[_]", tail)
            #print file_data #for debug purposes
            
            # angular limit for rotated face frontalization
            face_rot = -20
            
            #Copy only the images that have less than face_rot rotation angle
            if os.path.isfile(filepath): #and face_rot<float(file_data[1]):
    
                image = cv2.imread(filepath,1)# cv2.IMREAD_GRAYSCALE)

                if image is not None:
                    
                    # extract landmarks from the query image
                    # list containing a 2D array with points (x, y) for each face detected in the query image
                    lmarks = feature_detection.get_landmarks(image)
                    if lmarks.any():
                        # perform camera calibration according to the first face detected
                        proj_matrix, camera_matrix, rmat, tvec = calib.estimate_camera(model3D, lmarks[0])

                        # perform frontalization
                        frontal_raw, frontal_sym = frontalize.frontalize(image, proj_matrix, model3D.ref_U, eyemask)
                        #write frontal_sym to image file in pathdir location
                        out_file = os.path.join(pathdir,out_name)
                        print out_file
                        if not os.path.isfile(out_file):
                            #turn image to gray scale
                            gray_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
                            if gray_img is not None:
                                img = detect_face(gray_img, haar_face_cascade)
                                cv2.imwrite(out_file ,img)
                                print 'image converted...'
                            else:
                                print 'there is no image converted...'
                            print 'image created'
                        else:
                            print 'image already exists'
                        seek_or_write(filelist, out_file, x)

In [19]:
if __name__ == "__main__":
    
    mode = 'test'
    
    #Directories definition function
    #Directory to build processed dataset
    work_path = "/home/gonzalo/dev/post_data/MIT" #SCfaces"
    print work_path #for debug purposes
    make_sure_path_exists(work_path)
    #Directory to from where to extract data
    root_dir = "/home/gonzalo"
    make_sure_path_exists(root_dir)
    data_path = os.path.join(root_dir,"M9","Datasets","MIT-CBCL", 'test')#"training-synthetic") #,'SCface_database','mugshot_rotation_all') #
    print (data_path) #for debug purposes
    
    txt_file_list = os.path.join(work_path, mode,'list.txt')
    make_sure_file_exists(txt_file_list)
    
    #Set face detector
    if not os.path.isfile('/home/gonzalo/opencv-3.2.0/data/haarcascades/haarcascade_frontalface_alt.xml'):
        try:
            with open('/home/gonzalo/opencv-3.2.0/data/haarcascades/haarcascade_frontalface_alt.xml', 'r') as f:
                print 'haar_face_cascade loaded...'
        except OSError as error:
            if error.errno != errno.EEXIST:
                raise
    haar_face_cascade = cv2.CascadeClassifier('/home/gonzalo/opencv-3.2.0/data/haarcascades/haarcascade_frontalface_alt.xml')
    # check for dlib saved weights for face landmark detection
    # if it fails, dowload and extract it manually from
    # http://sourceforge.net/projects/dclib/files/dlib/v18.10/shape_predictor_68_face_landmarks.dat.bz2
    check.check_dlib_landmark_weights()
    # load detections performed by dlib library on 3D model and Reference Image
    model3D = frontalize.ThreeD_Model(path_to_face_front_utilyties + '/frontalization_models/model3Ddlib.mat', 'model_dlib')
    # load mask to exclude eyes from symmetry
    eyemask = np.asarray(io.loadmat(path_to_face_front_utilyties + '/frontalization_models/eyemask.mat')['eyemask'])
    
    # List of subjects numbers for folder creation
    name =["%04d" % x for x in range(10)] #for MIT-CBCL
    #name =["%03d" % x for x in range(1,131)] #for SCface
    #print name #for debug purposes
    
    # Launch frontalized faces dataset creation
    front_database_build(name, data_path, work_path, mode, eyemask, txt_file_list)
    print 'frontalization finished'
    

/home/gonzalo/dev/post_data/MIT
/home/gonzalo/M9/Datasets/MIT-CBCL/test
file found...
/home/gonzalo/dev/post_data/MIT/test/0000
/home/gonzalo/M9/Datasets/MIT-CBCL/test/0000*.pgm
0000_02225
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02225fr.jpg
Faces found:  1
[[19 17 81 81]]
image converted...
image created
0000_02732
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02732fr.jpg
Faces found:  1
[[19 18 79 79]]
image converted...
image created
0000_02967
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02967fr.jpg
Faces found:  1
[[23 20 78 78]]
image converted...
image created
0000_03522
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_03522fr.jpg
Faces found:  1
[[23 19 81 81]]
image converted...
image created
0000_05242
Number of faces detected: 1

Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02614fr.jpg
Faces found:  1
[[16 19 79 79]]
image converted...
image created
0000_02244
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02244fr.jpg
Faces found:  1
[[19 18 81 81]]
image converted...
image created
0000_02471
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02471fr.jpg
Faces found:  1
[[16 19 78 78]]
image converted...
image created
0000_02997
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02997fr.jpg
Faces found:  1
[[10 20 75 75]]
image converted...
image created
0000_03508
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_03508fr.jpg
Faces found:  1
[[31 21 76 76]]
image converted...
image created
0000_02628
Number of faces dete

Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02298fr.jpg
Faces found:  1
[[30 20 74 74]]
image converted...
image created
0000_02557
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02557fr.jpg
Faces found:  1
[[ 4 24 68 68]]
image converted...
image created
0000_02712
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02712fr.jpg
Faces found:  1
[[20 16 77 77]]
image converted...
image created
0000_03501
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_03501fr.jpg
Faces found:  1
[[33 22 74 74]]
image converted...
image created
0000_03375
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_03375fr.jpg
Faces found:  1
[[33 22 74 74]]
image converted...
image created
0000_02287
Number of faces dete

Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_05194fr.jpg
Faces found:  1
[[29 24 72 72]]
image converted...
image created
0000_02632
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02632fr.jpg
Faces found:  1
[[19 18 80 80]]
image converted...
image created
0000_05147
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_05147fr.jpg
Faces found:  1
[[19 19 75 75]]
image converted...
image created
0000_03773
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_03773fr.jpg
Faces found:  1
[[16 17 83 83]]
image converted...
image created
0000_02316
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02316fr.jpg
Faces found:  1
[[37 22 71 71]]
image converted...
image created
0000_02281
Number of faces dete

Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02291fr.jpg
Faces found:  1
[[30 21 75 75]]
image converted...
image created
0000_02827
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02827fr.jpg
Faces found:  1
[[23 19 80 80]]
image converted...
image created
0000_02558
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_02558fr.jpg
Faces found:  1
[[ 4 23 70 70]]
image converted...
image created
0000_03523
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_03523fr.jpg
Faces found:  1
[[22 19 81 81]]
image converted...
image created
0000_03528
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0000/0000_03528fr.jpg
Faces found:  1
[[21 19 81 81]]
image converted...
image created
0000_02597
Number of faces dete

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00302fr.jpg
Faces found:  1
[[22 14 69 69]]
image converted...
image created
0001_01284
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_01284fr.jpg
Faces found:  1
[[ 8  7 64 64]]
image converted...
image created
0001_00398
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00398fr.jpg
Faces found:  1
[[37 15 59 59]]
image converted...
image created
0001_01425
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_01425fr.jpg
Faces found:  1
[[14  6 71 71]]
image converted...
image created
0001_00556
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00556fr.jpg
Faces found:  1
[[ 9  9 69 69]]
image converted...
image created
0001_00555
Number of faces dete

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00502fr.jpg
Faces found:  1
[[32 15 62 62]]
image converted...
image created
0001_01417
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_01417fr.jpg
Faces found:  1
[[ 4  7 61 61]]
image converted...
image created
0001_00390
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00390fr.jpg
Faces found:  1
[[19 11 70 70]]
image converted...
image created
0001_01280
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_01280fr.jpg
Faces found:  1
[[ 7  6 65 65]]
image converted...
image created
0001_00682
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00682fr.jpg
Faces found:  1
[[36 14 61 61]]
image converted...
image created
0001_00729
Number of faces dete

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00727fr.jpg
Faces found:  1
[[30 12 64 64]]
image converted...
image created
0001_00303
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00303fr.jpg
Faces found:  1
[[19 13 70 70]]
image converted...
image created
0001_00742
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00742fr.jpg
Faces found:  1
[[ 3 15 61 61]]
image converted...
image created
0001_00547
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00547fr.jpg
Faces found:  1
[[ 9 10 70 70]]
image converted...
image created
0001_01265
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_01265fr.jpg
Faces found:  1
[[ 7  7 66 66]]
image converted...
image created
0001_00723
Number of faces dete

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00237fr.jpg
Faces found:  1
[[ 2 17 64 64]]
image converted...
image created
0001_00135
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00135fr.jpg
Faces found:  1
[[ 6 13 71 71]]
image converted...
image created
0001_00866
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00866fr.jpg
Faces found:  1
[[ 6 14 65 65]]
image converted...
image created
0001_01356
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_01356fr.jpg
Faces found:  1
[[10  6 70 70]]
image converted...
image created
0001_00680
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00680fr.jpg
Faces found:  1
[[34 13 62 62]]
image converted...
image created
0001_00393
Number of faces dete

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00120fr.jpg
Faces found:  1
[[ 7 14 68 68]]
image converted...
image created
0001_00314
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00314fr.jpg
Faces found:  1
[[ 3 17 62 62]]
image converted...
image created
0001_00554
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00554fr.jpg
Faces found:  1
[[ 9  9 69 69]]
image converted...
image created
0001_00301
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00301fr.jpg
Faces found:  1
[[22 14 69 69]]
image converted...
image created
0001_00659
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0001/0001_00659fr.jpg
Faces found:  1
[[ 2 11 60 60]]
image converted...
image created
0001_00311
Number of faces dete

Number of faces detected: 1
query image shape: (120, 120, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_je_00837fr.jpg
Faces found:  1
[[26 20 76 76]]
image converted...
image created
0002_j_01274
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01274fr.jpg
Faces found:  1
[[10  2 61 61]]
image converted...
image created
0002_j_01233
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01233fr.jpg
Faces found:  1
[[10  2 64 64]]
image converted...
image created
0002_j_01248
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01248fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0002_j_00793
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_00793fr.jpg
Faces found:  1
[[ 7  1 66 66]]
image converted...
image created
0002_j_01033
Num

Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_00606fr.jpg
Faces found:  1
[[ 8  2 67 67]]
image converted...
image created
0002_je_00205
Number of faces detected: 1
query image shape: (120, 120, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_je_00205fr.jpg
Faces found:  1
[[ 1 26 61 61]]
image converted...
image created
0002_j_01259
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01259fr.jpg
Faces found:  1
[[11  0 65 65]]
image converted...
image created
0002_j_01079
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01079fr.jpg
Faces found:  1
[[11  4 62 62]]
image converted...
image created
0002_je_00728
Number of faces detected: 1
query image shape: (120, 120, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_je_00728fr.jpg
Faces found:  1
[[10 20 81 81]]
image converted...
image created
0002_j_01018
Nu

Number of faces detected: 1
query image shape: (120, 120, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_je_00276fr.jpg
Faces found:  1
[[ 2 22 68 68]]
image converted...
image created
0002_j_01066
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01066fr.jpg
Faces found:  1
[[ 9  3 64 64]]
image converted...
image created
0002_j_01072
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01072fr.jpg
Faces found:  1
[[20 25 46 46]]
image converted...
image created
0002_j_01207
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01207fr.jpg
Faces found:  1
[[ 9  3 65 65]]
image converted...
image created
0002_j_01195
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01195fr.jpg
Faces found:  1
[[ 9  3 65 65]]
image converted...
image created
0002_01293
Number of

Number of faces detected: 1
query image shape: (120, 120, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_je_00832fr.jpg
Faces found:  1
[[22 20 80 80]]
image converted...
image created
0002_j_01246
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01246fr.jpg
Faces found:  1
[[22 26 47 47]]
image converted...
image created
0002_j_01123
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01123fr.jpg
Faces found:  1
[[ 6  2 65 65]]
image converted...
image created
0002_01071
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_01071fr.jpg
Faces found:  1
[[ 7 23 60 60]]
image converted...
image created
0002_je_00642
Number of faces detected: 1
query image shape: (120, 120, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_je_00642fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0002_j_01096
N

Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01061fr.jpg
Faces found:  1
[[ 9  1 65 65]]
image converted...
image created
0002_01333
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_01333fr.jpg
Faces found:  1
[[18 17 68 68]]
image converted...
image created
0002_j_01078
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01078fr.jpg
Faces found:  1
[[ 8  3 65 65]]
image converted...
image created
0002_j_01143
Number of faces detected: 1
query image shape: (82, 82, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_j_01143fr.jpg
Faces found:  1
[[ 7  2 62 62]]
image converted...
image created
0002_je_00090
Number of faces detected: 1
query image shape: (120, 120, 3)
/home/gonzalo/dev/post_data/MIT/test/0002/0002_je_00090fr.jpg
Faces found:  1
[[36 26 68 68]]
image converted...
image created
0002_j_01309
Number o

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01646fr.jpg
Faces found:  1
[[18  3 66 66]]
image converted...
image created
0003_01935
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01935fr.jpg
Faces found:  1
[[ 4  4 63 63]]
image converted...
image created
0003_01219
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01219fr.jpg
Faces found:  1
[[ 2  2 64 64]]
image converted...
image created
0003_01168
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01168fr.jpg
Faces found:  1
[[27  3 63 63]]
image converted...
image created
0003_00663
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_00663fr.jpg
Faces found:  1
[[ 7  3 68 68]]
image converted...
image created
0003_02044
Number of faces dete

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_02132fr.jpg
Faces found:  1
[[ 2  5 58 58]]
image converted...
image created
0003_01517
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01517fr.jpg
Faces found:  1
[[42  2 56 56]]
image converted...
image created
0003_00812
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_00812fr.jpg
Faces found:  1
[[18  3 66 66]]
image converted...
image created
0003_01789
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01789fr.jpg
Faces found:  1
[[ 2  2 61 61]]
image converted...
image created
0003_02122
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_02122fr.jpg
Faces found:  1
[[ 3  3 59 59]]
image converted...
image created
0003_01627
Number of faces dete

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_00726fr.jpg
Faces found:  1
[[28  4 64 64]]
image converted...
image created
0003_01594
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01594fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0003_00617
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_00617fr.jpg
Faces found:  1
[[ 8  4 70 70]]
image converted...
image created
0003_01661
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01661fr.jpg
Faces found:  1
[[10  2 66 66]]
image converted...
image created
0003_01622
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01622fr.jpg
Faces found:  1
[[34  3 62 62]]
image converted...
image created
0003_01812
Number of faces 

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01149fr.jpg
Faces found:  1
[[37  4 57 57]]
image converted...
image created
0003_02098
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_02098fr.jpg
Faces found:  1
[[ 9  2 67 67]]
image converted...
image created
0003_02117
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_02117fr.jpg
Faces found:  1
[[ 4  3 60 60]]
image converted...
image created
0003_00777
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_00777fr.jpg
Faces found:  1
[[32  4 63 63]]
image converted...
image created
0003_00664
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_00664fr.jpg
Faces found:  1
[[ 7  3 68 68]]
image converted...
image created
0003_01623
Number of faces dete

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01820fr.jpg
Faces found:  1
[[ 4  4 61 61]]
image converted...
image created
0003_01796
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0003/0003_01796fr.jpg
Faces found:  1
[[ 5  4 63 63]]
image converted...
image created
/home/gonzalo/dev/post_data/MIT/test/0004
/home/gonzalo/M9/Datasets/MIT-CBCL/test/0004*.pgm
0004_ct_00000
Number of faces detected: 1
query image shape: (110, 110, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00000fr.jpg
Faces found:  1
[[10 18 68 68]]
image converted...
image created
0004_ct_00043
Number of faces detected: 1
query image shape: (110, 110, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00043fr.jpg
Faces found:  1
[[11 17 69 69]]
image converted...
image created
0004_ct_00022
Number of faces detected: 1
query image shape: (110, 110, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_c

Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00815fr.jpg
Faces found:  1
[[ 3 23 65 65]]
image converted...
image created
0004_ct_01281
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_01281fr.jpg
Faces found:  1
[[16 21 69 69]]
image converted...
image created
0004_ct_00028
Number of faces detected: 1
query image shape: (78, 78, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00028fr.jpg
Faces found:  1
[[ 7  2 58 58]]
image converted...
image created
0004_06970
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_06970fr.jpg
Faces found:  1
[[18  5 65 65]]
image converted...
image created
0004_06897
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_06897fr.jpg
Faces found:  1
[[36  8 60 60]]
image converted...
image created
0004_ct_00023
Numb

Number of faces detected: 1
query image shape: (78, 78, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00008fr.jpg
Faces found:  1
[[ 7  1 56 56]]
image converted...
image created
0004_06846
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_06846fr.jpg
Faces found:  1
[[15  7 68 68]]
image converted...
image created
0004_ct_00189
Number of faces detected: 1
query image shape: (78, 78, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00189fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0004_ct_00373
Number of faces detected: 1
query image shape: (110, 110, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00373fr.jpg
Faces found:  1
[[27 17 69 69]]
image converted...
image created
0004_ct_00801
Number of faces detected: 1
query image shape: (110, 110, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00801fr.jpg
Faces found:  1
[[11 20 76 76]]
image converted...
image created
0004_ct_00

Number of faces detected: 1
query image shape: (110, 110, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00920fr.jpg
Faces found:  1
[[29 19 66 66]]
image converted...
image created
0004_07072
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_07072fr.jpg
Faces found:  1
[[ 4  8 57 57]]
image converted...
image created
0004_ct_00017
Number of faces detected: 1
query image shape: (110, 110, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00017fr.jpg
Faces found:  1
[[11 17 70 70]]
image converted...
image created
0004_ct_00146
Number of faces detected: 1
query image shape: (78, 78, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00146fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0004_ct_00758
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00758fr.jpg
Faces found:  1
[[14 21 71 71]]
image converted...
image created
0004_068

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_06851fr.jpg
Faces found:  1
[[15  7 68 68]]
image converted...
image created
0004_06905
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_06905fr.jpg
Faces found:  1
[[42  7 56 56]]
image converted...
image created
0004_06902
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_06902fr.jpg
Faces found:  1
[[43  7 56 56]]
image converted...
image created
0004_ct_00015
Number of faces detected: 1
query image shape: (110, 110, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_ct_00015fr.jpg
Faces found:  1
[[10 17 71 71]]
image converted...
image created
0004_07059
Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0004/0004_07059fr.jpg
Faces found:  1
[[ 4  7 57 57]]
image converted...
image created
0004_ct_00143
Number of f

Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_mt_00702fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_jt_00384
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_jt_00384fr.jpg
Faces found:  1
[[ 7  0 56 56]]
image converted...
image created
0005_00061
Number of faces detected: 1
query image shape: (105, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_00061fr.jpg
Faces found:  1
[[12 10 81 81]]
image converted...
image created
0005_jt_00337
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_jt_00337fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_jt_00276
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_jt_00276fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_m

Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_m_00510fr.jpg
Faces found:  1
[[ 3  0 65 65]]
image converted...
image created
0005_jt_00060
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_jt_00060fr.jpg
Faces found:  1
[[ 5  1 60 60]]
image converted...
image created
0005_a00294
Number of faces detected: 1
query image shape: (105, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_a00294fr.jpg
Faces found:  1
[[25 18 71 71]]
image converted...
image created
0005_mt_00425
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_mt_00425fr.jpg
Faces found:  1
[[ 3  1 59 59]]
image converted...
image created
0005_004021
Number of faces detected: 1
query image shape: (62, 62, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_004021fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_mt_00756
Num

Number of faces detected: 1
query image shape: (100, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_00405fr.jpg
Faces found:  1
[[16 12 73 73]]
image converted...
image created
0005_003831
Number of faces detected: 1
query image shape: (62, 62, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_003831fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_mt_00547
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_mt_00547fr.jpg
Faces found:  1
[[11  1 57 57]]
image converted...
image created
0005_jt_00034
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_jt_00034fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_jt_00421
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_jt_00421fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_00

Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_mt_00795fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_00391
Number of faces detected: 1
query image shape: (105, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_00391fr.jpg
Faces found:  1
[[16 12 78 78]]
image converted...
image created
0005_jt_00035
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_jt_00035fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_007671
Number of faces detected: 0
0005_mt_00430
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_mt_00430fr.jpg
Faces found:  1
[[ 2  1 61 61]]
image converted...
image created
0005_a00779
Number of faces detected: 1
query image shape: (105, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_a00779fr.jpg
Faces found:  1
[[ 8 18 69 69]]
image

Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_mt_00078fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_mt_02149
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_mt_02149fr.jpg
Faces found:  1
[[ 8  1 52 52]]
image converted...
image created
0005_mt_00811
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_mt_00811fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_m_00348
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_m_00348fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0005_mt_00470
Number of faces detected: 1
query image shape: (80, 80, 3)
/home/gonzalo/dev/post_data/MIT/test/0005/0005_mt_00470fr.jpg
Faces found:  1
[[ 3  2 60 60]]
image converted...
image created
0005

Number of faces detected: 1
query image shape: (150, 108, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per154_-1048576000fr.jpg
Faces found:  1
[[13 27 81 81]]
image converted...
image created
0006_per309_-1614807040
Number of faces detected: 1
query image shape: (149, 108, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per309_-1614807040fr.jpg
Faces found:  1
[[16 27 79 79]]
image converted...
image created
0006_per167_1983905792
Number of faces detected: 1
query image shape: (141, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per167_1983905792fr.jpg
Faces found:  1
[[ 9 25 80 80]]
image converted...
image created
0006_per264_1556086784
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per264_1556086784fr.jpg
Faces found:  1
[[25 34 70 70]]
image converted...
image created
0006_per73_-268435456
Number of faces detected: 1
query image shape: (141, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per73_-268

Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per182_-1832910848fr.jpg
Faces found:  1
[[14 29 78 78]]
image converted...
image created
0006_per87_-759169024
Number of faces detected: 1
query image shape: (135, 97, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per87_-759169024fr.jpg
Faces found:  1
[[10 20 80 80]]
image converted...
image created
0006_per101_-1472200704
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per101_-1472200704fr.jpg
Faces found:  0
()
none faces found
image converted...
image created
0006_per70_-1333788672
Number of faces detected: 1
query image shape: (150, 108, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per70_-1333788672fr.jpg
Faces found:  1
[[11 27 81 81]]
image converted...
image created
0006_per162_-1992294400
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per162_

0006_per299_-1111490560
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per299_-1111490560fr.jpg
Faces found:  1
[[16 29 83 83]]
image converted...
image created
0006_per249_-524288000
Number of faces detected: 1
query image shape: (141, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per249_-524288000fr.jpg
Faces found:  1
[[ 9 27 77 77]]
image converted...
image created
0006_per305_-2034237440
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per305_-2034237440fr.jpg
Faces found:  1
[[15 25 82 82]]
image converted...
image created
0006_per320_-859832320
Number of faces detected: 1
query image shape: (141, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per320_-859832320fr.jpg
Faces found:  1
[[ 9 25 80 80]]
image converted...
image created
0006_per316_-1686110208
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT

Number of faces detected: 1
query image shape: (156, 112, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per38_-557842432fr.jpg
Faces found:  1
[[13 28 81 81]]
image converted...
image created
0006_per144_1602224128
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per144_1602224128fr.jpg
Faces found:  1
[[12 26 85 85]]
image converted...
image created
0006_per104_394264576
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per104_394264576fr.jpg
Faces found:  1
[[17 34 73 73]]
image converted...
image created
0006_per28_-448790528
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per28_-448790528fr.jpg
Faces found:  1
[[19 32 73 73]]
image converted...
image created
0006_per139_1807745024
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per139_1807745024

Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per302_-1275068416fr.jpg
Faces found:  1
[[13 26 81 81]]
image converted...
image created
0006_per141_-1656750080
Number of faces detected: 1
query image shape: (150, 105, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per141_-1656750080fr.jpg
Faces found:  1
[[ 6 27 84 84]]
image converted...
image created
0006_per293_1841299456
Number of faces detected: 1
query image shape: (137, 97, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per293_1841299456fr.jpg
Faces found:  1
[[14 23 75 75]]
image converted...
image created
0006_per53_-562036736
Number of faces detected: 1
query image shape: (149, 108, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per53_-562036736fr.jpg
Faces found:  1
[[15 27 79 79]]
image converted...
image created
0006_per248_155189248
Number of faces detected: 1
query image shape: (141, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0006/0006_per248_155189

Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per189_503316480fr.jpg
Faces found:  1
[[14 22 68 68]]
image converted...
image created
0007_per11_977272832
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per11_977272832fr.jpg
Faces found:  1
[[14 24 63 63]]
image converted...
image created
0007_per41_1879048192
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per41_1879048192fr.jpg
Faces found:  1
[[13 24 66 66]]
image converted...
image created
0007_per158_-1472200704
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per158_-1472200704fr.jpg
Faces found:  1
[[15 25 65 65]]
image converted...
image created
0007_per177_1539309568
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per177_1539309568fr.jp

Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per127_-33554432fr.jpg
Faces found:  1
[[12 22 67 67]]
image converted...
image created
0007_per83_348127232
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per83_348127232fr.jpg
Faces found:  1
[[10 26 65 65]]
image converted...
image created
0007_per36_1426063360
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per36_1426063360fr.jpg
Faces found:  1
[[17 28 59 59]]
image converted...
image created
0007_per38_-2013265920
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per38_-2013265920fr.jpg
Faces found:  1
[[15 26 61 61]]
image converted...
image created
0007_per19_1086324736
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per19_1086324736fr.jpg
Fa

Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per46_281018368fr.jpg
Faces found:  1
[[13 23 66 66]]
image converted...
image created
0007_per149_1811939328
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per149_1811939328fr.jpg
Faces found:  1
[[11 27 64 64]]
image converted...
image created
0007_per83_1841299456
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per83_1841299456fr.jpg
Faces found:  1
[[13 24 65 65]]
image converted...
image created
0007_per158_-1430257664
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per158_-1430257664fr.jpg
Faces found:  1
[[12 23 66 66]]
image converted...
image created
0007_per15_2080374784
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per15_2080374784fr.j

Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per75_574619648fr.jpg
Faces found:  1
[[11 24 67 67]]
image converted...
image created
0007_per69_448790528
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per69_448790528fr.jpg
Faces found:  1
[[12 25 65 65]]
image converted...
image created
0007_per144_1094713344
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per144_1094713344fr.jpg
Faces found:  1
[[12 24 65 65]]
image converted...
image created
0007_per32_1069547520
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per32_1069547520fr.jpg
Faces found:  1
[[12 23 67 67]]
image converted...
image created
0007_per156_1312817152
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per156_1312817152fr.jpg
F

Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per26_-1740636160fr.jpg
Faces found:  1
[[12 27 63 63]]
image converted...
image created
0007_per28_-2109734912
Number of faces detected: 1
query image shape: (137, 99, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per28_-2109734912fr.jpg
Faces found:  1
[[14 27 74 74]]
image converted...
image created
0007_per143_-1912602624
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per143_-1912602624fr.jpg
Faces found:  1
[[14 24 65 65]]
image converted...
image created
0007_per160_-696254464
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per160_-696254464fr.jpg
Faces found:  1
[[16 24 64 64]]
image converted...
image created
0007_per23_780140544
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per23_780140544fr

Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per22_897581056fr.jpg
Faces found:  1
[[14 26 62 62]]
image converted...
image created
0007_per197_-1103101952
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per197_-1103101952fr.jpg
Faces found:  1
[[14 25 65 65]]
image converted...
image created
0007_per156_478150656
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per156_478150656fr.jpg
Faces found:  1
[[15 24 63 63]]
image converted...
image created
0007_per86_-1312817152
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per86_-1312817152fr.jpg
Faces found:  1
[[14 23 64 64]]
image converted...
image created
0007_per21_125829120
Number of faces detected: 1
query image shape: (122, 88, 3)
/home/gonzalo/dev/post_data/MIT/test/0007/0007_per21_125829120fr.jpg

Number of faces detected: 1
query image shape: (150, 108, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_per112_-1535115264fr.jpg
Faces found:  1
[[20 33 73 73]]
image converted...
image created
0008_123
Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_123fr.jpg
Faces found:  1
[[ 4 39 68 68]]
image converted...
image created
0008_32_-1220542464
Number of faces detected: 1
query image shape: (157, 112, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_32_-1220542464fr.jpg
Faces found:  1
[[12 32 80 80]]
image converted...
image created
0008_179
Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_179fr.jpg
Faces found:  1
[[ 3 38 71 71]]
image converted...
image created
0008_145
Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_145fr.jpg
Faces found:  1
[[ 3 33 81 81]]
image converted...
image created
0008_318_121

Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_181fr.jpg
Faces found:  1
[[ 2 39 69 69]]
image converted...
image created
0008_per356_-1463812096
Number of faces detected: 1
query image shape: (150, 108, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_per356_-1463812096fr.jpg
Faces found:  1
[[20 39 63 63]]
image converted...
image created
0008_98_-104857600
Number of faces detected: 1
query image shape: (139, 100, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_98_-104857600fr.jpg
Faces found:  1
[[ 8 23 75 75]]
image converted...
image created
0008_107
Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_107fr.jpg
Faces found:  1
[[ 4 37 73 73]]
image converted...
image created
0008_124
Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_124fr.jpg
Faces found:  1
[[ 3 36 73 73]]
image converted...
image created

Number of faces detected: 1
query image shape: (157, 112, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_368_-805306368fr.jpg
Faces found:  1
[[12 28 80 80]]
image converted...
image created
0008_per90_-369098752
Number of faces detected: 1
query image shape: (150, 108, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_per90_-369098752fr.jpg
Faces found:  1
[[16 34 76 76]]
image converted...
image created
0008_328_-482344960
Number of faces detected: 1
query image shape: (157, 112, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_328_-482344960fr.jpg
Faces found:  1
[[13 30 77 77]]
image converted...
image created
0008_182
Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_182fr.jpg
Faces found:  1
[[ 2 38 71 71]]
image converted...
image created
0008_117
Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_117fr.jpg
Faces found:  0
()
none faces found
image converted...


Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_130fr.jpg
Faces found:  1
[[ 2 37 70 70]]
image converted...
image created
0008_per446_-2088763392
Number of faces detected: 1
query image shape: (150, 108, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_per446_-2088763392fr.jpg
Faces found:  1
[[16 31 73 73]]
image converted...
image created
0008_per392_1862270976
Number of faces detected: 1
query image shape: (150, 108, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_per392_1862270976fr.jpg
Faces found:  1
[[16 34 69 69]]
image converted...
image created
0008_137
Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_137fr.jpg
Faces found:  1
[[ 6 35 77 77]]
image converted...
image created
0008_94_-1438646272
Number of faces detected: 1
query image shape: (157, 112, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_94_-1438646272fr.jpg
Faces found:  1
[[14 31 79 79]]
im

Number of faces detected: 1
query image shape: (150, 108, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_per380_-1103101952fr.jpg
Faces found:  1
[[18 28 79 79]]
image converted...
image created
0008_86_1094713344
Number of faces detected: 1
query image shape: (157, 112, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_86_1094713344fr.jpg
Faces found:  1
[[12 31 79 79]]
image converted...
image created
0008_270_-1522532352
Number of faces detected: 1
query image shape: (157, 112, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_270_-1522532352fr.jpg
Faces found:  1
[[13 31 77 77]]
image converted...
image created
0008_127
Number of faces detected: 1
query image shape: (165, 101, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_127fr.jpg
Faces found:  1
[[ 4 39 73 73]]
image converted...
image created
0008_302_-855638016
Number of faces detected: 1
query image shape: (157, 112, 3)
/home/gonzalo/dev/post_data/MIT/test/0008/0008_302_-855638016fr.jpg
Faces found:  1
[[13 29 79 79]]
i

Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05011fr.jpg
Faces found:  1
[[26 10 66 66]]
image converted...
image created
0009_05028
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05028fr.jpg
Faces found:  1
[[27 10 68 68]]
image converted...
image created
0009_05206
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05206fr.jpg
Faces found:  1
[[15  6 62 62]]
image converted...
image created
0009_05289
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05289fr.jpg
Faces found:  1
[[16  6 63 63]]
image converted...
image created
0009_04935
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_04935fr.jpg
Faces found:  1
[[29 10 64 64]]
image converted...
image created
0009_04970
Number of faces dete

Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05815fr.jpg
Faces found:  1
[[ 4  9 61 61]]
image converted...
image created
0009_05043
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05043fr.jpg
Faces found:  1
[[40  8 65 65]]
image converted...
image created
0009_05168
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05168fr.jpg
Faces found:  1
[[35  7 67 67]]
image converted...
image created
0009_05298
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05298fr.jpg
Faces found:  1
[[22  9 64 64]]
image converted...
image created
0009_04451
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_04451fr.jpg
Faces found:  1
[[41 12 68 68]]
image converted...
image created
0009_06042
Number of faces dete

Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05292fr.jpg
Faces found:  1
[[19  8 61 61]]
image converted...
image created
0009_04949
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_04949fr.jpg
Faces found:  1
[[22 10 66 66]]
image converted...
image created
0009_04462
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_04462fr.jpg
Faces found:  1
[[32 11 73 73]]
image converted...
image created
0009_05389
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05389fr.jpg
Faces found:  1
[[31  5 59 59]]
image converted...
image created
0009_05925
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05925fr.jpg
Faces found:  1
[[13  8 68 68]]
image converted...
image created
0009_04979
Number of faces dete

Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05184fr.jpg
Faces found:  1
[[27  7 65 65]]
image converted...
image created
0009_04660
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_04660fr.jpg
Faces found:  1
[[34  9 71 71]]
image converted...
image created
0009_04281
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_04281fr.jpg
Faces found:  1
[[27 12 74 74]]
image converted...
image created
0009_04471
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_04471fr.jpg
Faces found:  1
[[23 10 72 72]]
image converted...
image created
0009_04238
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_04238fr.jpg
Faces found:  1
[[29 12 72 72]]
image converted...
image created
0009_04220
Number of faces dete

Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05465fr.jpg
Faces found:  1
[[28 20 66 66]]
image converted...
image created
0009_04286
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_04286fr.jpg
Faces found:  1
[[27 12 74 74]]
image converted...
image created
0009_05637
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05637fr.jpg
Faces found:  1
[[22  7 62 62]]
image converted...
image created
0009_05411
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_05411fr.jpg
Faces found:  1
[[30  8 68 68]]
image converted...
image created
0009_04318
Number of faces detected: 1
query image shape: (115, 115, 3)
/home/gonzalo/dev/post_data/MIT/test/0009/0009_04318fr.jpg
Faces found:  1
[[41 14 66 66]]
image converted...
image created
frontalization finished
